### ISSUE TITLE
Stable sort metadata roles

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1368]
Some spurious diffs were created on https://github.com/terraform-google-modules/terraform-google-iam/pull/179 which I think is happening because we are not stable sorting the roles.
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/b6dcd6020ee637dfbe21f07bac8d0c31113475db/cli/bpmetadata/types.go#L50

**Comment by g-awmalik** [comment]
This isn't because of roles not being sorted but because there are multiple "Project" `level` nodes and there is no metadata to sort them effectively. This only happens when there are multiple test projects being provisioned with their own set of roles which is an edge case. I'd suggest we close this for now and revisit if this becomes more prevalent. WDYT?

**Comment by bharathkkb** [comment]
@g-awmalik Agreed it is an edge case. Could we come up with some heuristic just to reduce the unnecessary diff? Maybe num of roles for each node could be used to sort?
