### ISSUE TITLE
Integration tests for release-please automated PR's

### ISSUE THREAD

**Issue by davenportjw** [GoogleCloudPlatform/cloud-foundation-toolkit#1714]
Opening for consideration:
- Release please only changes the specific version and tags associated with a particular repo. As prior PR's require integration tests for specific code changes, should this PR also require integration tests given it is a tagging operation?

**Comment by bharathkkb** [comment]
I think our original goal with having integration tests was to validate that the release is WAI especially as more most repos do not perform periodic testing at head. Sometimes PRs are merged without rebasing or merging with main which can result in tests for the PR passing although they might fail due to something unrelated post merge which will be caught by release integration tests.
