### ISSUE TITLE
Add Concourse pipeline for Terraform SQL DB module

### ISSUE THREAD

**Issue by aaron-lane** [GoogleCloudPlatform/cloud-foundation-toolkit#189]
This pipeline should be implemented similar to the existing pipelines in `infra/concourse/pipelines` and Terraform resources should be added under `infra/terraform/test_fixtures`.

**Comment by kopachevsky** [comment]
@aaron-lane  is it already 0.12 compatible?

**Comment by kopachevsky** [comment]
@aaron-lane I do have question specific to SQL DB module CI, there are Terraform variables used for test fixtures like:

mysql_ha_name
mysql_simple_name
pg_simple_name
etc..
All those are DB names for each test case, the issue is if you do kitchen converge and kitchen destroy, twice you'll have error "You cannot reuse an instance name for up to a week after you have deleted an instance." https://cloud.google.com/sql/docs/mysql/delete-instance

Means we have to generate unique name on each test run. Is this functionality should be implemented on pipeline script side?
