### ISSUE TITLE
Module Swapper: terraform-google- requirement

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/cloud-foundation-toolkit#2065]
A few repos don't use the `terraform-google-` prefix.  E.g. `terraform-dynamic-python-webapp`, `terraform-large-data-sharing-java-webapp`

`Expected to find repo name prefixed with terraform-google-. Got: terraform-dynamic-python-webapp`

`Expected to find repo name prefixed with terraform-google-. Got: terraform-large-data-sharing-java-webapp`

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/420373f22d332767a7be2b252aa0dea28343fa3e/infra/module-swapper/cmd/swap.go#L88

**Comment by apeabody** [comment]
FYI @bharathkkb

**Comment by bharathkkb** [comment]
Hey @apeabody, I think this should now be fixed with  https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2056 downgrading this from an error- released in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2059 and in the latest 1.18x dev tools image. I retried the lint run in that repo and it passed

**Comment by apeabody** [comment]
Great! Yup, a run with dev-tools 1.18.4 looks good! :)
