### ISSUE TITLE
Unable to process unmanaged instance group with managed_instance_group.py

### ISSUE THREAD

**Issue by gdzieleziesz** [GoogleCloudPlatform/cloud-foundation-toolkit#288]
managed_instance_group.py doesn't give an option to create unmanaged instnace group. In case of creation of unmanaged instnace group instance template should not be required.

**Comment by ocsig** [comment]
Was your expectation from the ' Managed Instance Group' template to support 'Unmanaged Instance group' or you would rather looking for an ' Unmanaged Instance Group' Template? ( I understand the functional overlap, however the MIG template is much more complex because of the InstanceTemplate dependency. )

**Comment by gdzieleziesz** [comment]
Separate template just for the Unmanaged Instance Group would be the simplest solution. As you wrote it's much simpler than MIG template.
