### ISSUE TITLE
GKE template is incompatible with Python3

### ISSUE THREAD

**Issue by buhkguj** [GoogleCloudPlatform/cloud-foundation-toolkit#529]
Hi,
The dm/templates/gke/ template produces the following warning in DM newly:

> The template is incompatible with Python3. Please fix the following errors: Error compiling Python code: No module named 'packaging' Resource: gke.py Resource: config https://cloud.google.com/deployment-manager/docs/migrate-to-python3

**Comment by patrickmslatteryvt** [comment]
Yes, I'm getting that too, nothing I have tried fixes it.

**Comment by trevorjwilliams** [comment]
I believe it's only a warning, and so can be ignored for the moment.

However, it's caused by logic that looks to exist only to help with versions of kubernetes older than 1.12, which are no longer options from the web console at least. Consequently, you can get rid of the warning by deleting the corresponding logic, [as i did here](https://github.com/trevorjwilliams/cloud-foundation-toolkit/commit/5abcd362f118c7721cf10ba22d038517df421b73).

Not sure this is the preferred solution, however.

**Comment by morgante** [comment]
@trevorjwilliams Would you mind opening a PR with that fix? I agree we can drop support for Kubernetes versions older than 1.12.

**Comment by trevorjwilliams** [comment]
Sure, I'll update the version number, add a comment, and submit it.

**Comment by buhkguj** [comment]
PR fixed the warning. Thx!
